// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0ux5CCwEJA5h_r9F8B6a68qvolDx80iQ',
    appId: '1:393534396036:web:57bef878311157f46a94d1',
    messagingSenderId: '393534396036',
    projectId: 'family-finance-gmstyle-app',
    authDomain: 'family-finance-gmstyle-app.firebaseapp.com',
    storageBucket: 'family-finance-gmstyle-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWZHG4RfIOamDNTBBygtsXeNJFxvsRwKU',
    appId: '1:393534396036:android:526f6e1761e439126a94d1',
    messagingSenderId: '393534396036',
    projectId: 'family-finance-gmstyle-app',
    storageBucket: 'family-finance-gmstyle-app.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0ux5CCwEJA5h_r9F8B6a68qvolDx80iQ',
    appId: '1:393534396036:web:1cf0c2eed3102a5d6a94d1',
    messagingSenderId: '393534396036',
    projectId: 'family-finance-gmstyle-app',
    authDomain: 'family-finance-gmstyle-app.firebaseapp.com',
    storageBucket: 'family-finance-gmstyle-app.firebasestorage.app',
  );
}
